name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: iterative/setup-cml@v2

      - name: Check CML version
        run: cml --version

      - name: List files in workspace
        run: ls -l

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Main file
        run: python main.py

      - name: Run TEST
        run: python -m unittest discover

      - name: List files after tests
        run: ls -l

      - name: Create CML REPORT
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# First Line of our report" > report.md
          echo "## Bar Plots" >> report.md
          echo '![](./bars.png "Bar plot")' >> report.md
          echo "## Line Plots" >> report.md
          echo '![](./lines.png "Line plot")' >> report.md

          cml --debug comment create report.md

